#!/usr/bin/env node
// Mirror CLAUDE.md → AGENT.md so both Claude Code and other AI tooling
// (Cursor, Aider, Continue, generic AGENTS.md readers) see the same content.
// CLAUDE.md is the canonical source. Edit only CLAUDE.md.

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const src = path.join(root, 'CLAUDE.md');
const dst = path.join(root, 'AGENT.md');

if (!fs.existsSync(src)) {
  console.error(`✗ ${src} does not exist`);
  process.exit(1);
}

const content = fs.readFileSync(src, 'utf8');
const banner =
  '<!--\n' +
  '  Auto-generated from CLAUDE.md by `npm run sync-docs`.\n' +
  '  Do not edit this file directly — your changes will be overwritten on next build.\n' +
  '  Edit CLAUDE.md instead.\n' +
  '-->\n\n';

fs.writeFileSync(dst, banner + content, 'utf8');
console.log(`✓ Synced CLAUDE.md → AGENT.md (${content.length} chars)`);
